add cache in events to avoid duplication
kubeslice/kubeslice-monitoring pull request #26
Opened 2023-04-27 08:29 UTC by rahulsawra98

This PR adds a cache to eventRecorder that stores a unique key generated and event as a value.

2023-04-27 11:44 UTC, kmjayadeep requested changes
The approach looks good to me. I would suggest to add some test cases as well, since there might be some corner cases. 

I would propose to cover at least the following cases

- Creating event for the first time - make sure cache is updated
- Creating multiple events with mix and match of same and different attributes. Make sure that getEventKey is working as expected
- Invalidation of cache after a certain time period
- Validate event count

I think a table driven test would be the best approach here since there are so many cases to cover

2023-04-27 11:44 UTC, kmjayadeep commented on pkg/events/events.go
> +			er.Logger.With("error", err, "event", ev).Error("Unable to create event")
error should be returned back from the function

2023-04-27 11:44 UTC, kmjayadeep commented on pkg/events/events.go
> +			er.Logger.With("error", err, "event", ev).Error("Unable to update event")
error should be returned back from the function

2023-04-28 11:05 UTC, rahulsawra98 commented
> The approach looks good to me. I would suggest to add some test cases as well, since there might be some corner cases.
> 
> I would propose to cover at least the following cases
> 
> * Creating event for the first time - make sure cache is updated
> * Creating multiple events with mix and match of same and different attributes. Make sure that getEventKey is working as expected
> * Invalidation of cache after a certain time period
> * Validate event count
> 
> I think a table driven test would be the best approach here since there are so many cases to cover

Done! PTAL!

2023-04-28 11:29 UTC, PuranAdhikari approved these changes

2023-04-28 11:31 UTC, narmidm commented on pkg/events/events.go
> +		"")
please add - the project & name

2023-04-28 11:35 UTC, narmidm approved these changes

2023-04-28 11:35 UTC, merged